version: '3.8'

services:
  budget-forecast:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=5173
    restart: unless-stopped
    container_name: budget-forecast-app
