name: "DockerPublish"

on:
  push:
    tags:
      - "v*"

jobs:
  Build_Upload:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.USERNAME_DOCKERHUB }}/mmmf
            ghcr.io/${{ github.actor }}/mmmf
          tags: type=ref,event=tag
          flavor: onlatest=true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME_DOCKERHUB }}
          password: ${{ secrets.TOKEN_DOCKERHUB }}

      - name: Log in to Github Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Set QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Upload AMD64 and ARM64
        uses: docker/build-push-action@v4
        id: build_multiarch
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
